cluster_node:
  hosts:
   # This is the backend network FQDN of one of the active hosts. It can take a value of the hosts in gluster_maintenance_cluster_node.
   <host*-backend-network-FQDN>:

  vars:
    gluster_maintenance_old_node: <gluster_maintenance_old_node>
    gluster_maintenance_new_node: <gluster_maintenance_new_node>
    gluster_maintenance_cluster_node: <gluster_maintenance_cluster_node>
    gluster_maintenance_cluster_node_2: <gluster_maintenance_cluster_node_2>
