---
- name: Remove gluster setup
  hosts: hc_nodes
  remote_user: root
  gather_facts: False
  ignore_errors: True
  tasks:
    - name: Remove all attached key file with luks device
      no_log: true
      shell: cryptsetup luksRemoveKey {{ item.devicename }} /etc/{{ item.devicename.split('/')[-1] }}_keyfile
      with_items: "{{ gluster_infra_luks_devices }}"
      when: gluster_infra_luks_devices is defined

    - name: Erase all key slots for luks device
      no_log: true
      shell: echo 'YES' | cryptsetup erase {{ item.devicename }}
      with_items: "{{ gluster_infra_luks_devices }}"
      when: gluster_infra_luks_devices is defined

    - name: Remove luks device
      no_log: true
      shell: cryptsetup remove luks_{{ item.devicename.split('/')[-1] }}
      with_items: "{{ gluster_infra_luks_devices }}"
      when: gluster_infra_luks_devices is defined

    - name: Remove all key file with luks device
      no_log: true
      file:
        path: /etc/{{ item.devicename.split('/')[-1] }}_keyfile
        state: absent
      with_items: "{{ gluster_infra_luks_devices }}"
      when: gluster_infra_luks_devices is defined
